# Generated by Django 3.0.14 on 2022-05-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rated_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(),
        ),
    ]
