# Generated by Django 3.0.14 on 2022-05-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20220528_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
