# Generated by Django 3.0.14 on 2022-05-28 05:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_auto_20220528_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Ratings',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='rate',
            new_name='rating',
        ),
    ]
